#!/bin/bash

echo "Thank you for installing Mercury for Linux, to learn about how to use Mercury please go to the README, also be sure to check out our other software and tools!"




sudo chmod u+x cmdscan
sudo cp cmdscan /usr/local/bin/

sudo chmod u+x cmdip
sudo cp cmdip /usr/local/bin/

sudo chmod u+x cmddisconnect
sudo cp cmddisconnect /usr/local/bin/






