#!/bin/bash

echo "Thank you for installing CMDSecure for Linux, to learn about how to use CMDSecure please go to the README"




sudo chmod u+x cmdscan
sudo cp cmdscan /usr/local/bin/

sudo chmod u+x cmdip
sudo cp cmdip /usr/local/bin/

sudo chmod u+x cmddisconnect
sudo cp cmddisconnect /usr/local/bin/






